name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install radon xenon
          pip install -e ".[dev]"

      - name: Check code complexity
        run: |
          xenon --max-absolute B --max-modules B --max-average A intelliagent
          radon cc intelliagent -a -nb

      - name: Check maintainability index
        run: |
          radon mi intelliagent -s

      - name: Run pylint
        run: |
          pip install pylint
          pylint intelliagent --fail-under=9.0
