name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0" # Run weekly

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit safety
          pip install -e ".[dev]"

      - name: Run Bandit
        run: |
          bandit -r intelliagent -ll

      - name: Run Safety
        run: |
          safety check

      - name: Run pip-audit
        run: |
          pip install pip-audit
          pip-audit
